services:
  # Main Laravel Application
  - type: web
    name: college-placement-portal
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /healthz
    envVars:
      # Application
      - key: APP_NAME
        value: College Placement Portal
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://college-placement-portals.onrender.com
      - key: APP_KEY
        sync: false
      
      # Logging
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_STACK
        value: single
      
      # Database (Supabase PostgreSQL) - Using direct connection for better reliability
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.wkqbukidxmzbgwauncrl.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.wkqbukidxmzbgwauncrl
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      
      # Cache & Session
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: QUEUE_CONNECTION
        value: sync
      
      # CSRF Protection
      - key: SANCTUM_STATEFUL_DOMAINS
        value: college-placement-portals.onrender.com
      
      # Security
      - key: TRUSTED_PROXIES
        value: "*"
      
      # PHP Configuration
      - key: PHP_MEMORY_LIMIT
        value: 256M
      - key: PHP_MAX_EXECUTION_TIME
        value: 60
      
      # RAG Service Connection
      - key: RAG_SERVICE_URL
        fromService:
          type: web
          name: rag-service
          property: host
      - key: RAG_SERVICE_TIMEOUT
        value: 30
      - key: RAG_ENABLED
        value: true
      
      # Groq API (for RAG)
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_TEMPERATURE
        value: 0.7
      - key: GROQ_MAX_TOKENS
        value: 1024

  # Python FastAPI RAG Service
  - type: web
    name: rag-service
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./python-rag/Dockerfile
    dockerContext: ./python-rag
    healthCheckPath: /health
    envVars:
      # Service Configuration
      - key: PORT
        value: 8001
      - key: DEBUG
        value: false
      
      # Database Connection (for knowledge sync) - Using direct connection
      - key: DB_HOST
        value: db.wkqbukidxmzbgwauncrl.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.wkqbukidxmzbgwauncrl
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      
      # OpenRouter API
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: meta-llama/llama-3.1-70b-instruct
      - key: OPENROUTER_TEMPERATURE
        value: 0.7
      - key: OPENROUTER_MAX_TOKENS
        value: 1024
      
      # ChromaDB Configuration
      - key: CHROMA_PERSIST_DIR
        value: ./chromadb_storage
      - key: CHROMA_COLLECTION_NAME
        value: placement_knowledge
